default:
    password: ENC[AES256_GCM,data:kcZBNfHoIcN4,iv:RadYSWfaQhrCp85UGK1dTZIMBaKSlSnpMVeW1V67G8o=,tag:gs8VSZMIVBTkRtpNO9UX1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19vzt3ha7s8zdhfrf308mkcuggr2yxdak3ktg828975asy77ewcksaf64et
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYS205RzAyYnNobVZRdW56
            VnZQTFlIRWMvWnhFWlRMT1RabDRrKzlLM1Y0CmtCdU9lQ0hqUVFOaS9DeHNoMXUw
            UEg3b09ONjVYM2M0dkYwb2dPMFVGN1UKLS0tIGhOTXZMRmNxUVdFMXVyVGxYeHNK
            K08yTGZnTW85dSs1alJnTTBaVHE5SmsKeN0W7yx/3vO2wSGJjItm9jgUoeyY0+Vq
            7B9MEG4lS2oZtQgS1pThaexEE6rtPgudnUTuutLXeTGDTB4HsVK5ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-02T17:01:25Z"
    mac: ENC[AES256_GCM,data:OZq/s+RRvNJ8WJ/sDRY87W1JmhgHBmtcQuKjFG+sP01CftrUsnxhvtCkk9ZWy5DeiEJOJcquE2bgq2ibBc+Zjnq3RhpPfxtEa/FN8YkTIwVjGxp8ViTRaEtCvXZUEkMV8LmV40b232slGv8l49CAjNOwK0UOlA8etkxOFh6v66k=,iv:ziN6Ogw2iZXsnW+rnFoD8n2ZSA6rha92YV54NJn9v5c=,tag:WXLIaLlXMHdryKy5IyH2UA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
