default:
    password: ENC[AES256_GCM,data:08hZmQ==,iv:Ye9iisK4ArVLbAk4Q1eJ0X0OqC5Chjwj85Rjq2+yLc4=,tag:mDXsIugjd1GJbOVA5s1tEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19vzt3ha7s8zdhfrf308mkcuggr2yxdak3ktg828975asy77ewcksaf64et
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYS205RzAyYnNobVZRdW56
            VnZQTFlIRWMvWnhFWlRMT1RabDRrKzlLM1Y0CmtCdU9lQ0hqUVFOaS9DeHNoMXUw
            UEg3b09ONjVYM2M0dkYwb2dPMFVGN1UKLS0tIGhOTXZMRmNxUVdFMXVyVGxYeHNK
            K08yTGZnTW85dSs1alJnTTBaVHE5SmsKeN0W7yx/3vO2wSGJjItm9jgUoeyY0+Vq
            7B9MEG4lS2oZtQgS1pThaexEE6rtPgudnUTuutLXeTGDTB4HsVK5ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T09:24:06Z"
    mac: ENC[AES256_GCM,data:RkKSHkZ0lqqCoh578zgDkwQkbYJ1tvOrw5Qo8/dXIRvKhBqz6bNN/pTX1YuFnI2RX+4shlNlcWBvfalfqaCpMVoT229wpshhDtsJETnDbL/A+FnIvIMts3rUQGxNvLNxnzsGKocgghblS8epH2IygNp+eTJy6ulYYTTuA51rIts=,iv:adTZ22t/lxlB053cjOxwQHL6UUCZP9m0K48iZP0LVio=,tag:pEsxgS9Scct9B/LtxKpxQw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
